version: "3.8"
services:
  db:
    image: postgres:15
    container_name: news_db
    env_file: 
      - .env-non-dev
    ports:
      - 5432:5432 

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7
    container_name: reviews_redis
    ports:
      - 6379:6379

    
  celery_beat:
    build:
      context: .
    container_name: reviews_celery_beat
    command: sh -c "celery --app=app.tasks.celery:celery worker -l INFO -B"
    env_file:
      - .env-non-dev
    depends_on:
      - redis
      - db

  reviews:
    build:
      context: .
    container_name: news_app
    env_file:
      - .env-non-dev
    command: ["docker/app.sh"]
    ports:
      - 4444:8000
    depends_on:
      - db
      - redis
      - celery_beat

  frontend:
      build:
        context: templates/
      container_name: frontend_app
      command: "http-server dist"
      ports:
        - 5468:80
      depends_on:
        - reviews



volumes:
  postgresdata: