FROM node:alpine as build
WORKDIR /templates
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /templates/dist /usr/share/nginx/html
WORKDIR /app
COPY --from=build /templates/nginx.conf /etc/nginx/sites-avalaible/default
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]